package besterp.sherlock221b.com.besterp.db.model;

import besterp.sherlock221b.com.besterp.db.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import besterp.sherlock221b.com.besterp.db.dao.CustomDao;
import besterp.sherlock221b.com.besterp.db.dao.ProductDao;
import besterp.sherlock221b.com.besterp.db.dao.ProductStandardDao;
import besterp.sherlock221b.com.besterp.db.dao.PurchaserAccountDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PURCHASER_ACCOUNT".
 */
public class PurchaserAccount {

    private Long id;
    private int purchaserAccountNumber;
    private double purchaserAccountPrice;
    private double purchaserAccountTotal;
    /** Not-null value. */
    private java.util.Date purchaserDate;
    private String desc;
    private boolean isDelete;
    /** Not-null value. */
    private java.util.Date crtTime;
    /** Not-null value. */
    private java.util.Date updateTime;
    private Long productId;
    private Long standardId;
    private Long customId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient PurchaserAccountDao myDao;

    private Product product;
    private Long product__resolvedKey;

    private ProductStandard productStandard;
    private Long productStandard__resolvedKey;

    private Custom custom;
    private Long custom__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PurchaserAccount() {
    }

    public PurchaserAccount(Long id) {
        this.id = id;
    }

    public PurchaserAccount(Long id, int purchaserAccountNumber, double purchaserAccountPrice, double purchaserAccountTotal, java.util.Date purchaserDate, String desc, boolean isDelete, java.util.Date crtTime, java.util.Date updateTime, Long productId, Long standardId, Long customId) {
        this.id = id;
        this.purchaserAccountNumber = purchaserAccountNumber;
        this.purchaserAccountPrice = purchaserAccountPrice;
        this.purchaserAccountTotal = purchaserAccountTotal;
        this.purchaserDate = purchaserDate;
        this.desc = desc;
        this.isDelete = isDelete;
        this.crtTime = crtTime;
        this.updateTime = updateTime;
        this.productId = productId;
        this.standardId = standardId;
        this.customId = customId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getPurchaserAccountDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getPurchaserAccountNumber() {
        return purchaserAccountNumber;
    }

    public void setPurchaserAccountNumber(int purchaserAccountNumber) {
        this.purchaserAccountNumber = purchaserAccountNumber;
    }

    public double getPurchaserAccountPrice() {
        return purchaserAccountPrice;
    }

    public void setPurchaserAccountPrice(double purchaserAccountPrice) {
        this.purchaserAccountPrice = purchaserAccountPrice;
    }

    public double getPurchaserAccountTotal() {
        return purchaserAccountTotal;
    }

    public void setPurchaserAccountTotal(double purchaserAccountTotal) {
        this.purchaserAccountTotal = purchaserAccountTotal;
    }

    /** Not-null value. */
    public java.util.Date getPurchaserDate() {
        return purchaserDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPurchaserDate(java.util.Date purchaserDate) {
        this.purchaserDate = purchaserDate;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public boolean getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(boolean isDelete) {
        this.isDelete = isDelete;
    }

    /** Not-null value. */
    public java.util.Date getCrtTime() {
        return crtTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCrtTime(java.util.Date crtTime) {
        this.crtTime = crtTime;
    }

    /** Not-null value. */
    public java.util.Date getUpdateTime() {
        return updateTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdateTime(java.util.Date updateTime) {
        this.updateTime = updateTime;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Long getStandardId() {
        return standardId;
    }

    public void setStandardId(Long standardId) {
        this.standardId = standardId;
    }

    public Long getCustomId() {
        return customId;
    }

    public void setCustomId(Long customId) {
        this.customId = customId;
    }

    /** To-one relationship, resolved on first access. */
    public Product getProduct() {
        Long __key = this.productId;
        if (product__resolvedKey == null || !product__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ProductDao targetDao = daoSession.getProductDao();
            Product productNew = targetDao.load(__key);
            synchronized (this) {
                product = productNew;
            	product__resolvedKey = __key;
            }
        }
        return product;
    }

    public void setProduct(Product product) {
        synchronized (this) {
            this.product = product;
            productId = product == null ? null : product.getId();
            product__resolvedKey = productId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public ProductStandard getProductStandard() {
        Long __key = this.standardId;
        if (productStandard__resolvedKey == null || !productStandard__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ProductStandardDao targetDao = daoSession.getProductStandardDao();
            ProductStandard productStandardNew = targetDao.load(__key);
            synchronized (this) {
                productStandard = productStandardNew;
            	productStandard__resolvedKey = __key;
            }
        }
        return productStandard;
    }

    public void setProductStandard(ProductStandard productStandard) {
        synchronized (this) {
            this.productStandard = productStandard;
            standardId = productStandard == null ? null : productStandard.getId();
            productStandard__resolvedKey = standardId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Custom getCustom() {
        Long __key = this.customId;
        if (custom__resolvedKey == null || !custom__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CustomDao targetDao = daoSession.getCustomDao();
            Custom customNew = targetDao.load(__key);
            synchronized (this) {
                custom = customNew;
            	custom__resolvedKey = __key;
            }
        }
        return custom;
    }

    public void setCustom(Custom custom) {
        synchronized (this) {
            this.custom = custom;
            customId = custom == null ? null : custom.getId();
            custom__resolvedKey = customId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
