package besterp.sherlock221b.com.besterp.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import besterp.sherlock221b.com.besterp.db.model.Product;

import besterp.sherlock221b.com.besterp.db.model.ProductStandard;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRODUCT_STANDARD".
*/
public class ProductStandardDao extends AbstractDao<ProductStandard, Long> {

    public static final String TABLENAME = "PRODUCT_STANDARD";

    /**
     * Properties of entity ProductStandard.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StandardName = new Property(1, String.class, "standardName", false, "STANDARD_NAME");
        public final static Property IsDelete = new Property(2, boolean.class, "isDelete", false, "IS_DELETE");
        public final static Property CrtTime = new Property(3, java.util.Date.class, "crtTime", false, "CRT_TIME");
        public final static Property UpdateTime = new Property(4, java.util.Date.class, "updateTime", false, "UPDATE_TIME");
        public final static Property ProductId = new Property(5, Long.class, "productId", false, "PRODUCT_ID");
    };

    private DaoSession daoSession;

    private Query<ProductStandard> product_StandardsQuery;

    public ProductStandardDao(DaoConfig config) {
        super(config);
    }
    
    public ProductStandardDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRODUCT_STANDARD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"STANDARD_NAME\" TEXT," + // 1: standardName
                "\"IS_DELETE\" INTEGER NOT NULL ," + // 2: isDelete
                "\"CRT_TIME\" INTEGER NOT NULL ," + // 3: crtTime
                "\"UPDATE_TIME\" INTEGER NOT NULL ," + // 4: updateTime
                "\"PRODUCT_ID\" INTEGER);"); // 5: productId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRODUCT_STANDARD\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ProductStandard entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String standardName = entity.getStandardName();
        if (standardName != null) {
            stmt.bindString(2, standardName);
        }
        stmt.bindLong(3, entity.getIsDelete() ? 1L: 0L);
        stmt.bindLong(4, entity.getCrtTime().getTime());
        stmt.bindLong(5, entity.getUpdateTime().getTime());
 
        Long productId = entity.getProductId();
        if (productId != null) {
            stmt.bindLong(6, productId);
        }
    }

    @Override
    protected void attachEntity(ProductStandard entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ProductStandard readEntity(Cursor cursor, int offset) {
        ProductStandard entity = new ProductStandard( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // standardName
            cursor.getShort(offset + 2) != 0, // isDelete
            new java.util.Date(cursor.getLong(offset + 3)), // crtTime
            new java.util.Date(cursor.getLong(offset + 4)), // updateTime
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // productId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ProductStandard entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStandardName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIsDelete(cursor.getShort(offset + 2) != 0);
        entity.setCrtTime(new java.util.Date(cursor.getLong(offset + 3)));
        entity.setUpdateTime(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setProductId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ProductStandard entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ProductStandard entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "standards" to-many relationship of Product. */
    public List<ProductStandard> _queryProduct_Standards(Long productId) {
        synchronized (this) {
            if (product_StandardsQuery == null) {
                QueryBuilder<ProductStandard> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ProductId.eq(null));
                product_StandardsQuery = queryBuilder.build();
            }
        }
        Query<ProductStandard> query = product_StandardsQuery.forCurrentThread();
        query.setParameter(0, productId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getProductDao().getAllColumns());
            builder.append(" FROM PRODUCT_STANDARD T");
            builder.append(" LEFT JOIN PRODUCT T0 ON T.\"PRODUCT_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ProductStandard loadCurrentDeep(Cursor cursor, boolean lock) {
        ProductStandard entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Product product = loadCurrentOther(daoSession.getProductDao(), cursor, offset);
        entity.setProduct(product);

        return entity;    
    }

    public ProductStandard loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ProductStandard> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ProductStandard> list = new ArrayList<ProductStandard>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ProductStandard> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ProductStandard> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
